 //for dynamic card adding 
  const projects = [
    {
        title: "Project 1",
        description: "Description of project 1",
        image: "path/to/image1.jpg",
        link: "https://example.com/project1"
    },
    {
        title: "Project 2",
        description: "Description of project 2",
        image: "path/to/image2.jpg",
        link: "https://example.com/project2"
    },
    {
        title: "Project 3",
        description: "Description of project 3",
        image: "path/to/image2.jpg",
        link: "https://example.com/project2"
    },
    // can add more projects here as needed
];